workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.miapp.webviewapp"
      java: 17
    scripts:
      - name: Set executable permission for gradlew
        script: chmod +x ./gradlew
      - name: Build release APK
        script: ./gradlew :app:assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - carlosespinosa526@gmail.com
