workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Set executable permission for gradlew
        script: chmod +x ./gradlew
      - name: Clean project
        script: ./gradlew clean
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - carlosespinosa526@gmail.com
