workflows:
  android-release:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
